appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: GHWVIJ3N0TWFGqgT6J82TA7YY4SWOOViXua3nmik4z7zCELTd86KTx9gw6MXkHCJ9vLc0C8XS/9tUTKWxoq5nUOZe38Aw+5BB5cizWYdCiOoxopXYHs/fjU0kacKkGXyoO5sPLZ7JaiG2hOLKgIb4jKyPdwJ4Ic/jVpCr/nbSsGm++Kg7b+oGRuTtEk8gx4zOrOayGcJsnwGz/0CrsMNL7I627u5t1jzqmjswA3/PAfvivGr10USwslEIqt1xjCN7dEV+vXWB/Cme49eF9r217Pfo5PisOUCCmN+XqU2mhUMjnYT0S1GrBrV9TwpS3MAHjb+uT8uRgiWx5gB2WOuVkABmurZngBBmZPZdtEileFVUkXKLGcliv3/8ro0K6kH1MS4UcxGUNudOH291HTH2PHG9fRu0gV2+AnbetGKEGNsXMnVSrkuNAzPDn6gymDJqgg0tPSRwq7r9MAi57xJ7uasL4oc7qP/EiVTndgokWDwLSSvXq+ZbmnCq6ugFg+LZqIkt35egjyjDlZCo8yQRfG8S56UgZcL8pzxMsPL+kbZzzyIMPPv29u/FXVCYmZ5+PEeupDaYXzU1FlreHyrnqIZZFvV+RAww1PcBohWJ1Lj1v5bqGXt1bnXdETsRZFYvr05zmccGWWVXiwtgduO6KHRVva6VFlbRAUDc9CJ92o=}
